### ISSUE TITLE
Visual issue with chat box

### ISSUE THREAD

**Issue by tooomm** [Senryoku/MTGADraft#397]
Draft direction icon is not covered by expanded chat:
![image](https://user-images.githubusercontent.com/9874850/224832592-3c715c0e-b91a-4c53-9ff1-26de14e05312.png)

**Comment by Senryoku** [comment]
Should be fixed by 01cde830b1fa858df9a59c706387a51b8beb8b32
![image](https://user-images.githubusercontent.com/1338143/226203449-2ba25e45-1cd2-4633-aec9-0dcc9c1c923a.png)

**Comment by tooomm** [comment]
This is not yet deployed, right? I'm still seeing the same issue.

**Comment by Senryoku** [comment]
> This is not yet deployed, right? I'm still seeing the same issue.

No it wasn't, but it is now!

**Comment by tooomm** [comment]
Fixed
